api/urls.py
from django.urls import path

from . import views
app_name = 'api'
urlpatterns = [
  path('todo/list/', views.ApiTodoLV.as_view(), name='index'),
  path('todo/<int:pk>/delete/', views.ApiToDelV.as_view(), name='delete'),
  path('todo/create/', views.ApiTodoCV.as_view(), name='create'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomeView.as_view(), name='home'),
    path('todo/', include('todo.urls')),
    path('api/', include('api.urls')),

]

todo/urls.py
from django.urls import path

from . import views
app_name = 'todo'
urlpatterns = [
  path('', views.TodoTV.as_view(), name='index'),

]

api/models.py
from django.db import models

# Create your models here.

todo/models.py
from django.db import models

# Create your models here.


class Todo(models.Model):
    name = models.CharField('NAME', max_length=5, blank=True)
    todo = models.CharField('TODO', max_length=50)

    def __str__(self):
        return self.todo

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if not self.name:
            self.name = '홍길동'
        super().save()

api/views.py
import json

from django.forms import model_to_dict
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt

from django.views.generic.edit import BaseDeleteView, BaseCreateView
from django.views.generic.list import BaseListView

from todo.models import Todo


class ApiTodoLV(BaseListView):
    model = Todo

    def render_to_response(self, context, **response_kwargs):
        todoList = list(context['object_list'].values())
        return JsonResponse(data=todoList, safe=False)


class ApiToDelV(BaseDeleteView):
    model = Todo

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return JsonResponse(data={}, status=204)


class ApiTodoCV(BaseCreateView):
    model = Todo

    fields = '__all__'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['data'] = json.loads(self.request.body)
        return kwargs

    def form_valid(self, form):
        print('from valid', form)
        self.object = form.save()
        newTodo = model_to_dict(self.object)
        return JsonResponse(data=newTodo, status=201)

    def form_invalid(self, form):
        print('invalid', form)
        print('invalid', self.request.POST)
        print('invalid', self.request.body.decode('UTF8'))
        return JsonResponse(data=form.errors, status=400)

mysite/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'home.html'

todo/views.py
from django.views.generic import TemplateView


class TodoTV(TemplateView):
    template_name = 'todo/todo_index.html'

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}home.html{%endblock%}</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css" integrity="sha384-SZXxX4whJ79/gErwcOYf+zWLeJdY/qpuqC4cAa9rOGUstPomtqpuNWT9wdPEn2fk" crossorigin="anonymous">
    <link rel="icon" href="{% static '/img/favicon.ico' %}">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    {% block extra-style%} {% endblock %}
   {% block extra-script%} {% endblock %}
    </head>


<body style="padding-top:90px;">


<nav class="navbar navbar-expand-sm navbar-dark bg-primary fixed-top">

     <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Vue-Django System</span>


     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNAV">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Home</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'todo:index' %}">Todo</a></li>
            <li class="nav-item mx-1 btn btn-primary">
                <a class="nav-link text-white" href="{% url 'home' %}">Blog(tobe)</a></li>


            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Util</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
                    <div class="dropdown-divider"></div>
                </div>
            </li>
        </ul>

      <form class="form-inline my-2">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" >
       </form>



        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-primary">
                <a class="nav-link dropdown-toggle text-white" href="" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&nbsp; Anonymous &nbsp;</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'home' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'home' %}">Register</a>
                </div>
            </li>
        </ul>
    </div>

</nav>

<div class="container">
    {%block content%} {%endblock%}
</div>

<div>
    {%block footer%}{%endblock%}
</div>

{%block inner-script%} {%endblock%}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}home.html{% endblock %}

{% block extra-style %}
<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
{% endblock %}

{% block content %}
    <div class="home-window">
        <h2 class="title">Django - Python Web Programming</h2>
        <h4 class="powered"><i class="fas fa-cog"></i> powered by django and bootstrap.</h4>
    </div>

    <hr style="margin: 10px 0;">

    <div class="row text-center">
        <div class="col-sm-6">
            <h3>Todo App</h3>
            <p>With Todo app, you can manage, prioritize, and complete the most important things
                you need to do every day. I can focus on the most important things
                and I can do my day more deliberately.
                You can also share lists with colleagues, friends, and family.</p>
        </div>
        <div class="col-sm-6">
            <h3>Blog App</h3>
            <p>This application makes it possible to log daily events or write your own interests
                such as hobbies, techniques, etc.
                A typical blog combines text, digital images, and links to other blogs, web pages,
                and other media related to its topic.</p>
        </div>
    </div>
{% endblock %}

{% block footer %}
/*<footer class="fixed-bottom footer-wrapper">
      <!--

       <div class="container">
        <div class="row">
            <div class="col-md-4">
                <p>Copyright &copy; 2019 DjangoBook by shkim</p>
            </div>
            <div class="col-md-8">
                <ul class="list-inline float-right">
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Introduction</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Help</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Policy</a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="준비중입니다">Something</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</footer>

      -->
{% endblock %}

{% block extra-script%}

{% endblock  %}

todo/templates/todo/todo_index.html
{% extends 'base.html' %}

{% load static %}

{% block title%}Vue & Django todo app{% endblock %}

{% block extra-style %}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
{% endblock %}

{% block extra-script %}
 <script src="{% static 'main.js' %}" defer></script>
 <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
  <script src="https://unpkg.com/vue/dist/vue.min.js"></script>
{% endblock %}

{% block content %}
    <div id='app'>

        <h1>My Todo App !</h1>
        <strong>서로 할 일이나 의견을 공유해 봅시다.</strong>
        <br>



        <div class="inputBox">
            <input class="name" type="text" placeholder="name ..." v-model.trim="name">
            <input class="item" type="text" placeholder="type anything welcomed ..." v-model.trim="todo" v-on:keyup.enter="add_todo()">
            <button class="btn btn-primary btn-sm" v-on:click="add_todo()">ADD</button>
        </div>

        <ul class="todoList">
            <li v-for="(todo, index) in todoList">
                <span>[[ todo.name ]]:: [[ todo.todo ]]</span>
                <span class="removeBtn" v-on:click="remove_todo(todo, index)">X</span>
            </li>
        </ul>

    </div>

    {% endblock %}